{
	"major": [
		{"name": "Mr. Bennet", "description": "of Longbourn-house, Hertfordshire. Entailed estate with £2,000 a year. Married to Mrs. Bennet."},
		{"name": "Mrs. Bennet", "description": "Nee Gardiner of Meryton with a £5,000 dowry. Sister of Edward Gardiner of Gracechurch Street, London and Mrs. Phillips of Meryton. Children: Jane, Elizabeth, Mary, Catherine and Lydia"},
		{"name": "Miss Jane Bennet", "description": "Eldest unmarried Bennet daughter. Age 22. Dowry of £1,000. Marries Charles Bingley"},
		{"name": "Miss Elizabeth Bennet", "aliases": ["Lizzie"], "description": "Heroine. Second unmarried Bennet daughter. Age 20. Dowry of £1,000. A reputed beauty with fine eyes. Nicknames Eliza & Lizzy. Marries Fitzwilliam Darcy"},
		{"name": "Miss Mary Bennet", "description": "Third unmarried Bennet daughter. Dowry of £1,000. Pedantic"},
		{"name": "Miss Catherine Bennet", "aliases": ["Kitty"], "description": "Fourth unmarried Bennet daughter. Dowry of £1,000. Nickname Kitty"},
		{"name": "Miss Lydia Bennet", "description": "Fifth unmarried Bennet daughter. Age15. Dowry of £1,000. Marries George Wickham"},
		{"name": "Mr. Charles Bingley", "description": "of Netherfield Park and London. Age 22. Parents deceased. Inherited £100,000. Brother of Louisa and Caroline. Marries Jane Bennet"},
		{"name": "Mr. Hurst", "description": "of Grosvenor street, London. Married Louisa Bingley"},
		{"name": "Mrs. Louisa Hurst", "description": "of Grosvenor street, London. Nee Bingley with £20,000 dowry. Parents deceased. Sister to Charles and Caroline"},
		{"name": "Miss Caroline Bingley", "description": "of Netherfield Park and London. Unmarried with a £20,000 dowry. Parents deceased. Sister of Charles and Louisa"},
		{"name": "Sir William Lucas", "description": "of Lucas Lodge, Hertfordshire. Knight. Married to Lady Lucas. Neighbor of the Bennet’s"},
		{"name": "Lady Lucas", "description": "of Lucas Lodge. Married to Sir William Lucas. Children: Charlotte, Maria and unnamed girls and boys"},
		{"name": "Miss Charlotte Lucas", "description": "Eldest unmarried Lucas daughter. Age 27. Sister of Maria. Friend of Elizabeth’s. Marries Mr. Collins"},
		{"name": "Miss Maria Lucas", "description": "Unmarried younger Lucas daughter. Sister of Charlotte"},
		{"name": "Mr. Phillips", "description": "of Meryton. Attorney. Married ___ Gardiner"},
		{"name": "Mrs. Phillips", "description": "of Meryton. Nee Gardiner. Married to Mr. Phillips. Sister of Edward Gardiner and Mrs. Bennet"},
		{"name": "Sir Lewis de Bourgh", "description": "of Rosings Park, Kent. Married Lady Catherine Fitzwilliam. Deceased"},
		{"name": "Rt. Hon. Lady Catherine de Bourgh", "description": "of Rosings Park. Nee Fitzwilliam. Daughter of an Earl.  Widow of Sir Lewis de Bourgh. Sister of unnamed brother and Lady Anne Darcy. Children: Anne. Nephews: Col. Fitzwilliam and Fitzwilliam Darcy"},
		{"name": "Miss Anne de Bourgh", "description": "of Rosings Park. Unmarried de Bourgh daughter. Sickly. Promised in marriage to Mr. Darcy"},
		{"name": "Colonel Fitzwilliam", "description": "Unmarried younger son of an Earl. Nephew of Lady Catherine de Bourgh. Cousin of Fitzwilliam and Georgiana Darcy"},
		{"name": "Rev. William Collins", "description": "of Hunsford Parsonage, Kent. Rector by Lady Catherine’s patronage. Cousin and heir of Mr. Bennet. Marries Charlotte Lucas"},
		{"name": "Mr. Darcy (the elder)", "description": "of Pemberley, Derbyshire. Married Lady Anne Fitzwilliam. Deceased. Children: Fitzwilliam and Georgiana"},
		{"name": "Lady Anne Darcy", "description": "of Pemberley. Nee Fitzwilliam. Daughter of an Earl. Married Mr. Darcy. Deceased. Sister of Lady Catherine de Bourgh. Children Fitzwilliam and Georgiana."},
		{"name": "Mr. Fitzwilliam Darcy", "description": "Hero. Of Pemberley, Derbyshire and London. Unmarried eldest son and heir with £10,000 a year. Age 28. Nephew of Lady Catherine de Bourgh. Brother of Georgina. Cousin of Col. Fitzwilliam. Marries Elizabeth Bennet"},
		{"name": "Miss Georgiana Darcy", "description": "of Pemberley and London. Unmarried Darcy daughter. Age 16. Niece of Lady Catherine de Bourgh. Sister of Fitzwilliam. Cousin of Col Fitzwilliam"},
		{"name": "Colonel Forster", "description": "Commanding Officer of the ___shire Militia stationed in Meryton"},
		{"name": "Mrs. Harriet Forster", "description": "Col. Forster’s wife"},
		{"name": "Mr. George Wickham", "description": "A Lieutenant of the ___shire Militia. Son of Mr. Wickham, Mr. Darcy’s (the elder) stewart. Attended Cambridge University"},
		{"name": "Mr. Edward Gardiner", "description": "of Gracechurch street, London. Married to Mrs. Gardiner. Brother of Mrs. Bennet and Mrs. Phillips. Uncle of the Bennet daughters."},
		{"name": "Mrs. Gardiner", "description": "of Gracechurch street, London. Married to Edward Gardiner. Aunt of the Bennet daughters. Children: unnamed"}
	],
	"minor": [
		{"name": "Mrs. Annesley", "description": "Companion to Miss Darcy"},
		{"name": "Captain Carter", "description": "An officer of the ___shire Militia"},
		{"name": "Mr. Chamberlayne", "description": "A soldier of the ___shire Militia"},
		{"name": "Dawson", "description": "Lady Catherine de Bourgh’s lady’s maid"},
		{"name": "Mr. Denny", "description": "A solider of the ___shire Militia"},
		{"name": "Mr. William Goulding", "description": "of Haye-Park"},
		{"name": "Miss. Grantley", "description": "An acquaintance of Miss Bingley’s"},
		{"name": "Mr. Haggerston", "description": "Mr. Gardiner’s man of business"},
		{"name": "Harriet Harrington", "description": "An acquaintance of Lydia’s in Brighton"},
		{"name": "Miss Pen Harrington", "description": "An acquaintance of Lydia’s in Brighton"},
		{"name": "Mrs. Hill", "description": "The housekeeper at Longbourn-house"},
		{"name": "Mrs. Jenkinson", "description": "A companion to Anne de Bourgh"},
		{"name": "Mr. Jones", "description": "The apothecary of Meryton"},
		{"name": "John", "description": "A servant of either the Collins’ or Gardiners"},
		{"name": "Miss Mary King", "description": "An heiress with £10,000 that Wickham attempts to woo"},
		{"name": "Mrs. Long", "description": "The Bennet’s neighbor"},
		{"name": "Lady Metcalfe", "description": "An acquaintance of Lady Catherine"},
		{"name": "Mr. Morris", "description": "Land agent in Meryton who shows Netherfield Park to Mr. Bingley"},
		{"name": "Mrs. Nicholls", "description": "The housekeeper at Netherfield Park"},
		{"name": "Miss Pope", "description": "A governess in Lady Metcalf’s family"},
		{"name": "Mr. Pratt", "description": "A soldier of the ___shire Militia"},
		{"name": "Mrs. Reynolds", "description": "The housekeeper at Pemberley"},
		{"name": "Mr. Richard", "description": "An employee of Mr. Phillips"},
		{"name": "Mr. Robinson", "description": "An attendee of the Meryton Assembly"},
		{"name": "Mr. Stone", "description": "An employee of Mr. Gardiner"},
		{"name": "Miss Watson", "description": "A resident of Meryton"},
		{"name": "The Miss Webbs", "description": "Acquaintances of Lady Catherine de Bourgh"},
		{"name": "Mr. Wickham", "description": "A former steward to the late Mr. Darcy. Deceased"},
		{"name": "Mrs. Younge", "description": "A former companion of Miss Darcy"}
	]
}